### ISSUE TITLE
Auto-Increment version

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#108]
**Is your feature request related to a problem? Please describe.**

With CI/CD practices, the CD usually will pick up the latest release version.  With our GitHub action, the push uses the version from the YAML file.  This can result in someone accidentally forgetting to increment the version on change.

**Propose a solution**

There needs to be a way for the version in bus.yaml to be automatically incremented.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by pkedy** [comment]
Yes, it would be nice to be able to drive this off the git tag, instead of the YAML (when the project is built from git).

**Comment by jsoverson** [comment]
Closing as part of the rust migration
