### ISSUE TITLE
Package artifact type something other than "iota"

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#117]
**Is your feature request related to a problem? Please describe.**

Currently, the `artifactType = "application/vnd.nanobus.iota.v1+json"`.

https://github.com/nanobus/nanobus/blob/cd9a58bdca6ae19d9abe88a3f5f8b30c7253a048/pkg/oci/push.go#L19

This is misleading as the package contains the bus.yaml, and static files and other files. I think those are not considered part of Iotas.

**Propose a solution**

Perhaps we can call this `artifactType = "application/vnd.nanobus.package.v1+json"`

**Describe alternatives you've considered**

`application/vnd.nanobus.app.v1+json`
`application/vnd.nanobus.artifact.v1+json`

**Additional context**

None

**Comment by jsoverson** [comment]
Closing as part of the rust migration
