### ISSUE TITLE
Details regarding logging http actions

### ISSUE THREAD

**Issue by salgatt** [candlecorp/wasmflow#129]
**Is your feature request related to a problem? Please describe.**

While I'm seeing the server startup, I'm not seeing anything logged for the requests sent into my `http` server. I was able to create a server that used a log step but I'm not sure what variables are available for this. https://raw.githubusercontent.com/nanobus/examples/main/basic-web-service/bus.yaml

**Propose a solution**

Provide a way for developers to log information regarding requests received such as host, inputs..etc..

**Describe alternatives you've considered**

Like I noted above, I'm attempting to make use of the log action but not sure what variables to include. A better method would be a way to set logging and logging levels on the http transport.

**Additional context**

**Comment by jsoverson** [comment]
Thanks for the issue @salgatt. We're migrating this project back to rust but the go version will continue to be maintained at https://github.com/nanobus/nanobus.

I'm closing this issue because it pertains more to the Go version.
