### ISSUE TITLE
Document source of variables, ctx, system variables et al

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#92]
**Is your feature request related to a problem? Please describe.**

In nanobus, there are some variables that are populated by filters or other processes without clear understanding that they are being returned or set.

**Propose a solution**

One example is the sub variable that is set by the session filter. The components that return variables should be made very clear (explicit) and should have a returns yaml key for those components where the return variable name can be specified by the developer.

In instances where we want to have some help would be some type of context variables or system variables. For example. some system variables could be like current date / time. Context variables could include parsed/enriched data. For instance if we automatically do geoIP lookup on end user IP address, that could be placed in a ctx variable. The system and ctx variables should be immutable using the YAML and read only during pipelines. They should only be set via nanobus or the system running nanobus. This could be used in a multi-tenant way to allow for adding the tenant or org ID into the scope.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by jsoverson** [comment]
Closing as part of the rust migration
