### ISSUE TITLE
Initializer for resources should be part of resources.yaml

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#94]
**Is your feature request related to a problem? Please describe.**
Currently the initializer needs to be part of the bus.yaml and needs the credentials that are also required in the resources.yaml resource definition.  It would make more sense if the initializer did not need to have the connection string and just referenced the resource by name like the interfaces and providers do.

**Propose a solution**
Make it so the initializer block does not need the connection string at all.  Just the name of the resource as defined in the `resource.yaml`.

**Describe alternatives you've considered**
An alternative that I considered was to make the initializer block a part of the resource definition in the resources.yaml.  I think this is not the correct SDLC and segregation of duties where the devops team would provision the resources and provide the connection string but the developer would not need to touch it and the devops team would not really be involved in the migration / initialization paths.

**Additional context**

None

**Comment by jsoverson** [comment]
Closing as part of the rust migration
