### ISSUE TITLE
Reference Iota by OCI registry tag

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#95]
**Is your feature request related to a problem? Please describe.**

Currently, running an Iota requires that it has been compiled into a WASM with its apex file exists on the local filesystem.

**Propose a solution**

I should be able to upload the Iota to the registry and just calling the iota by the registry tag and not having it exist locally.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by jsoverson** [comment]
Closing as part of the rust migration
